### ISSUE TITLE
TypeError: Cannot read property 'animations' of undefined

### ISSUE THREAD

**Issue by ghatul** [vyakymenko/angular2-seed-express#21]
version 2.0.1 

/node_modules/@angular/compiler/bundles/compiler.umd.js:8766
          template.animations.forEach(function (entry) { triggerLookup.add(entry.name); });
                  ^
TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:8766:19)
    at TemplateParseVisitor.visitElement (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:8749:20)
    at Element.visit (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:4688:78)
    at /home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:4703:31
    at Array.forEach (native)
    at visitAll (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:4702:13)
    at TemplateParser.tryParse (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/@angular/compiler/bundles/compiler.umd.js:8492:24)
    at Object.exports.parseTemplate (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/codelyzer/angular/templateParser.js:14:23)
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (/home/pooja/Desktop/development2.0/tpl-web-fullstack-seed/node_modules/codelyzer/angular/ng2Walker.js:115:62)
    at Array.forEach (native)

**Comment by vyakymenko** [comment]
@ghatul , how do you import `animation` ?

**Comment by vyakymenko** [comment]
Close since this is not a seed issue .
